### ISSUE TITLE
Sweep: go to apps/web/src/App.tsx and add element to JSX body<h2>CHATTII</h2>

### ISSUE THREAD

**Issue by ahmdammarr** [ahmdammarr/chatti#37]
### Details

in `apps/web/src/App.tsx` add `<h2>CHATTII</h2>` to the JSX elements

<details>
<summary>Checklist</summary>

- [X] `apps/web/src/App.tsx`
> * Add the `<h2>CHATTII</h2>` element to the JSX body in the `App` component.

</details>

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by ahmdammarr** [comment]
sweep: Retry
